use std::sync::Arc;

use axum::http;
use reqwest::{StatusCode, Url};
use rustls::pki_types::CertificateDer;
use tokio_tungstenite::{Connector, connect_async_tls_with_config, tungstenite::ClientRequestBuilder};
use tracing::{debug, trace};

use crate::{
    AccessToken, CommunicationProtocol, EndpointDescription, NodeId,
    common::negotiate_version,
    communication::{
        CommunicationResult, ConnectionInfo, Error, ErrorKind, NodeConfig, WebSocketTransport,
        wire::{
            CommunicationDetails, CommunicationDetailsErrorMessage, InitiateConnectionRequest, InitiateConnectionResponse, UnpairRequest,
        },
    },
};

/// Configuration for communication clients.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ClientConfig {
    /// Additional roots of trust for TLS connections. Useful when testing during the development of WAN endpoints.
    ///
    /// When the remote is on the LAN, this is not used.
    pub additional_certificates: Vec<CertificateDer<'static>>,
    /// Optional description of this endpoint, sent as update to the server.
    pub endpoint_description: Option<EndpointDescription>,
}

/// Client used to setup communication sessions for a node.
#[derive(Debug, Clone)]
pub struct Client {
    config: Arc<NodeConfig>,
    additional_certificates: Vec<CertificateDer<'static>>,
    endpoint_description: Option<EndpointDescription>,
}

/// A description of a pairing between two S2 Nodes.
///
/// This is provided as a trait to allow customization of the way in which storage of the
/// pairings is handled.
pub trait ClientPairing: Send {
    /// Type of the errors generated by the storage.
    type Error: std::error::Error + 'static;

    /// The Node ID of the S2 node initiating communication.
    fn client_id(&self) -> NodeId;
    /// The Node Id of the S2 node receiving the request to communicate.
    fn server_id(&self) -> NodeId;
    /// The currently stored access tokens for the connection.
    fn access_tokens(&self) -> impl AsRef<[AccessToken]>;
    /// The communication url the client can use to contact the server.
    fn communication_url(&self) -> impl AsRef<str>;

    /// Store a new set of access tokens for the pairing.
    fn set_access_tokens(&mut self, tokens: Vec<AccessToken>) -> impl Future<Output = Result<(), Self::Error>> + Send;
}

impl Client {
    /// Create a new client.
    pub fn new(config: ClientConfig, node_config: Arc<NodeConfig>) -> Self {
        Client {
            config: node_config,
            additional_certificates: config.additional_certificates,
            endpoint_description: config.endpoint_description,
        }
    }

    /// Unpair the given pairing. The caller is responsible for deleting the pairing
    /// upon success.
    #[tracing::instrument(skip_all, fields(client = %pairing.client_id(), server = %pairing.server_id()), level = tracing::Level::ERROR)]
    pub async fn unpair(&self, pairing: impl ClientPairing) -> CommunicationResult<()> {
        let client = reqwest::Client::builder()
            .tls_certs_merge(
                self.additional_certificates
                    .iter()
                    .filter_map(|v| reqwest::Certificate::from_der(v).ok()),
            )
            .build()
            .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;

        let communication_url = Url::parse(pairing.communication_url().as_ref()).map_err(|e| Error::new(ErrorKind::InvalidUrl, e))?;

        let version = negotiate_version(&client, communication_url.clone()).await?;

        match version {
            crate::common::wire::PairingVersion::V1 => {
                let base_url = communication_url.join("v1/").unwrap();

                let request = UnpairRequest {
                    client_node_id: pairing.client_id(),
                    server_node_id: pairing.server_id(),
                };

                for token in pairing.access_tokens().as_ref() {
                    let response = client
                        .post(base_url.join("unpair").unwrap())
                        .bearer_auth(&token.0)
                        .json(&request)
                        .send()
                        .await
                        .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;

                    if response.status() == StatusCode::UNAUTHORIZED {
                        debug!("Token was rejected by remote, assuming it is old.");
                        continue;
                    }

                    if response.status() != StatusCode::NO_CONTENT {
                        debug!(status = ?response.status(), "Unexpected status in response to initiateConnection request.");
                        return Err(ErrorKind::ProtocolError.into());
                    }

                    return Ok(());
                }

                Err(ErrorKind::NotPaired.into())
            }
        }
    }

    /// Establish a new connection with the server end of the given pairing.
    #[tracing::instrument(skip_all, fields(client = %pairing.client_id(), server = %pairing.server_id()), level = tracing::Level::ERROR)]
    pub async fn connect(&self, mut pairing: impl ClientPairing) -> CommunicationResult<ConnectionInfo> {
        trace!("Establishing new communication connection.");
        let client = reqwest::Client::builder()
            .tls_certs_merge(
                self.additional_certificates
                    .iter()
                    .filter_map(|v| reqwest::Certificate::from_der(v).ok()),
            )
            .build()
            .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;

        trace!("Prepared reqwest client.");

        let communication_url = Url::parse(pairing.communication_url().as_ref()).map_err(|e| Error::new(ErrorKind::InvalidUrl, e))?;

        let version = negotiate_version(&client, communication_url.clone()).await?;

        match version {
            crate::common::wire::PairingVersion::V1 => {
                let base_url = communication_url.join("v1/").unwrap();

                let request = InitiateConnectionRequest {
                    client_node_id: pairing.client_id(),
                    server_node_id: pairing.server_id(),
                    supported_message_versions: self.config.supported_message_versions.clone(),
                    supported_communication_protocols: vec![CommunicationProtocol("WebSocket".into())],
                    node_description: self.config.node_description().cloned(),
                    endpoint_description: self.endpoint_description.clone(),
                };

                let (initiate_response, current_token) = 'found: {
                    for token in pairing.access_tokens().as_ref() {
                        let response = client
                            .post(base_url.join("initiateConnection").unwrap())
                            .bearer_auth(&token.0)
                            .json(&request)
                            .send()
                            .await
                            .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;

                        if response.status() == StatusCode::UNAUTHORIZED {
                            debug!("Token was rejected by remote, assuming it is old.");
                            continue;
                        }

                        if response.status() == StatusCode::BAD_REQUEST {
                            let e = response
                                .json::<CommunicationDetailsErrorMessage>()
                                .await
                                .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;
                            return Err(match e {
                                CommunicationDetailsErrorMessage::IncompatibleS2MessageVersions
                                | CommunicationDetailsErrorMessage::IncompatibleCommunicationProtocols => {
                                    Error::new(ErrorKind::NoSupportedVersion, e)
                                }
                                CommunicationDetailsErrorMessage::NoLongerPaired => Error::new(ErrorKind::Unpaired, e),
                                CommunicationDetailsErrorMessage::ParsingError | CommunicationDetailsErrorMessage::Other => {
                                    Error::new(ErrorKind::ProtocolError, e)
                                }
                            });
                        }

                        if response.status() != StatusCode::OK {
                            debug!(status = ?response.status(), "Unexpected status in response to initiateConnection request.");
                            return Err(ErrorKind::ProtocolError.into());
                        }

                        break 'found (
                            response
                                .json::<InitiateConnectionResponse>()
                                .await
                                .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?,
                            token.clone(),
                        );
                    }

                    // Exhausted all the possible options.
                    return Err(ErrorKind::NotPaired.into());
                };

                if initiate_response.communication_protocol != CommunicationProtocol("WebSocket".into())
                    || !self.config.supported_message_versions.contains(&initiate_response.message_version)
                {
                    return Err(ErrorKind::NoSupportedVersion.into());
                }

                trace!("Initiated connection attempt.");

                pairing
                    .set_access_tokens(vec![current_token, initiate_response.access_token.clone()])
                    .await
                    .map_err(|e| Error::new(ErrorKind::Storage, Box::new(e) as Box<_>))?;

                trace!("Stored new access token.");

                let response = client
                    .post(base_url.join("confirmAccessToken").unwrap())
                    .bearer_auth(&initiate_response.access_token.0)
                    .send()
                    .await
                    .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;

                if response.status() != StatusCode::OK {
                    debug!(status = ?response.status(), "Unexpected response to confirmAccessToken request.");
                    return Err(ErrorKind::ProtocolError.into());
                }

                let communication_details = response
                    .json::<CommunicationDetails>()
                    .await
                    .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;

                trace!("Confirmed new access token to server.");

                pairing
                    .set_access_tokens(dbg!(vec![initiate_response.access_token]))
                    .await
                    .map_err(|e| Error::new(ErrorKind::Storage, Box::new(e) as Box<_>))?;

                trace!("Reduced stored access token to only new one.");

                match communication_details {
                    CommunicationDetails::WebSocket(web_socket_communication_details) => {
                        let tls_config_builder = rustls::ClientConfig::builder();
                        let cert_verifier = rustls_platform_verifier::Verifier::new_with_extra_roots(
                            self.additional_certificates.iter().cloned(),
                            tls_config_builder.crypto_provider().clone(),
                        )
                        .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;
                        let tls_config = tls_config_builder
                            .dangerous()
                            .with_custom_certificate_verifier(Arc::new(cert_verifier))
                            .with_no_client_auth();

                        let request = ClientRequestBuilder::new(
                            web_socket_communication_details
                                .websocket_url
                                .try_into()
                                .map_err(|e| Error::new(ErrorKind::ProtocolError, e))?,
                        )
                        .with_header(
                            http::header::AUTHORIZATION.as_str(),
                            format!("Bearer {}", web_socket_communication_details.websocket_token.0),
                        );

                        let (websocket, _) =
                            connect_async_tls_with_config(request, None, false, Some(Connector::Rustls(Arc::new(tls_config))))
                                .await
                                .map_err(|e| Error::new(ErrorKind::TransportFailed, e))?;

                        Ok(ConnectionInfo {
                            remote_node_description: initiate_response.node_description,
                            remote_endpoint_description: initiate_response.endpoint_description,
                            message_version: initiate_response.message_version,
                            transport: WebSocketTransport::new_client(websocket),
                        })
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::{
        convert::Infallible,
        net::{Ipv4Addr, SocketAddr},
        sync::{Arc, Mutex},
    };

    use axum::{Router, routing::post};
    use axum_server::{Handle, tls_rustls::RustlsConfig};
    use http::StatusCode;
    use rustls::pki_types::{CertificateDer, pem::PemObject};
    use s2energy_common::S2Transport;
    use tokio::net::TcpListener;

    use crate::{
        AccessToken, CommunicationProtocol, EndpointDescription, MessageVersion, NodeId, Role,
        common::wire::test::{UUID_A, UUID_B, basic_node_description},
        communication::{
            self, Client, ClientConfig, ClientPairing, ErrorKind, NodeConfig, PairingLookup, Server, ServerConfig, ServerPairing,
            ServerPairingStore,
            wire::{CommunicationDetailsErrorMessage, InitiateConnectionResponse},
        },
    };

    #[derive(Clone)]
    struct TestPairingStore {
        token: Arc<Mutex<AccessToken>>,
        last_request: Arc<Mutex<Option<PairingLookup>>>,
        config: NodeConfig,
        deleted: Arc<Mutex<bool>>,
    }

    impl TestPairingStore {
        fn new(token: AccessToken, config: NodeConfig) -> Self {
            Self {
                token: Arc::new(Mutex::new(token)),
                last_request: Arc::default(),
                config,
                deleted: Arc::default(),
            }
        }
    }

    impl ServerPairingStore for TestPairingStore {
        type Error = Infallible;

        type Pairing<'a>
            = &'a TestPairingStore
        where
            Self: 'a;

        async fn lookup(&self, request: PairingLookup) -> Result<communication::PairingLookupResult<Self::Pairing<'_>>, Self::Error> {
            *self.last_request.lock().unwrap() = Some(request);
            Ok(communication::PairingLookupResult::Pairing(self))
        }
    }

    impl ServerPairing for &TestPairingStore {
        type Error = Infallible;

        fn access_token(&self) -> impl AsRef<crate::AccessToken> {
            self.token.lock().unwrap().clone()
        }

        fn config(&self) -> impl AsRef<NodeConfig> {
            &self.config
        }

        async fn set_access_token(&mut self, token: crate::AccessToken) -> Result<(), Self::Error> {
            *self.token.lock().unwrap() = dbg!(token);
            Ok(())
        }

        async fn unpair(self) -> Result<(), Self::Error> {
            *self.deleted.lock().unwrap() = true;
            Ok(())
        }
    }

    struct TestPairing {
        client: NodeId,
        server: NodeId,
        tokens: Arc<Mutex<Vec<AccessToken>>>,
        url: String,
    }

    impl ClientPairing for &TestPairing {
        type Error = Infallible;

        fn client_id(&self) -> NodeId {
            self.server
        }

        fn server_id(&self) -> NodeId {
            self.client
        }

        fn access_tokens(&self) -> impl AsRef<[AccessToken]> {
            self.tokens.lock().unwrap().clone()
        }

        fn communication_url(&self) -> impl AsRef<str> {
            &self.url
        }

        async fn set_access_tokens(&mut self, tokens: Vec<AccessToken>) -> Result<(), Self::Error> {
            *self.tokens.lock().unwrap() = tokens;
            Ok(())
        }
    }

    async fn setup_server<S: ServerPairingStore>(
        store: S,
        endpoint: Option<EndpointDescription>,
        overrides: Router<()>,
    ) -> (Handle<SocketAddr>, Server<S>) {
        let rustls_config = RustlsConfig::from_pem(
            include_bytes!("../../testdata/localhost.chain.pem").into(),
            include_bytes!("../../testdata/localhost.key").into(),
        )
        .await
        .unwrap();
        let socket = TcpListener::bind(SocketAddr::new(Ipv4Addr::LOCALHOST.into(), 0)).await.unwrap();
        let addr = socket.local_addr().unwrap();
        let server = Server::new(
            ServerConfig {
                base_url: format!("localhost:{}", addr.port()),
                endpoint_description: endpoint,
            },
            store,
        );
        let http_server_handle = Handle::new();
        let axum_server = axum_server::from_tcp_rustls(socket.into_std().unwrap(), rustls_config)
            .unwrap()
            .handle(http_server_handle.clone())
            .serve(overrides.fallback_service(server.get_router()).into_make_service());
        tokio::spawn(async move {
            axum_server.await.unwrap();
        });

        (http_server_handle, server)
    }

    #[tokio::test]
    async fn unpair() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, _) = setup_server(store.clone(), None, Router::new()).await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        assert!(client.unpair(&pairing).await.is_ok());
        assert!(*store.deleted.lock().unwrap());
    }

    #[tokio::test]
    async fn unpair_unauthorized() {
        let (handle, _) = setup_server(
            TestPairingStore::new(
                AccessToken("testtoken".into()),
                NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            ),
            None,
            Router::new(),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("invalidtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        let error = client.unpair(&pairing).await.unwrap_err();
        assert_eq!(error.kind(), ErrorKind::NotPaired);
    }

    #[tokio::test]
    async fn succesfull_communication() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, mut server) = setup_server(store.clone(), None, Router::new()).await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        let mut client_connection = client.connect(&pairing).await.unwrap();
        assert_eq!(client_connection.message_version, MessageVersion("v1".into()));
        assert!(client_connection.remote_endpoint_description.is_none());
        assert!(client_connection.remote_node_description.is_none());
        assert_eq!(pairing.tokens.lock().unwrap().len(), 1);

        let (requested_pairing, mut server_connection) = server.next_connection().await;
        assert_eq!(requested_pairing, store.last_request.lock().unwrap().take().unwrap());
        assert_eq!(server_connection.message_version, MessageVersion("v1".into()));
        assert!(server_connection.remote_endpoint_description.is_none());
        assert!(server_connection.remote_node_description.is_none());

        client_connection.transport.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_connection.transport.receive::<String>().await.is_err());

        let mut client_connection = client.connect(&pairing).await.unwrap();
        assert_eq!(client_connection.message_version, MessageVersion("v1".into()));
        assert!(client_connection.remote_endpoint_description.is_none());
        assert!(client_connection.remote_node_description.is_none());

        let (requested_pairing, mut server_connection) = server.next_connection().await;
        assert_eq!(requested_pairing, store.last_request.lock().unwrap().take().unwrap());
        assert_eq!(server_connection.message_version, MessageVersion("v1".into()));
        assert!(server_connection.remote_endpoint_description.is_none());
        assert!(server_connection.remote_node_description.is_none());

        client_connection.transport.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_connection.transport.receive::<String>().await.is_err());

        handle.shutdown();
    }

    #[tokio::test]
    async fn send_endpoint_config() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, mut server) = setup_server(store.clone(), None, Router::new()).await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: Some(EndpointDescription {
                    name: Some("a".into()),
                    logo_url: Some("b".into()),
                    deployment: None,
                }),
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        let mut client_connection = client.connect(&pairing).await.unwrap();
        assert_eq!(client_connection.message_version, MessageVersion("v1".into()));
        assert!(client_connection.remote_endpoint_description.is_none());
        assert!(client_connection.remote_node_description.is_none());

        let (requested_pairing, mut server_connection) = server.next_connection().await;
        assert_eq!(requested_pairing, store.last_request.lock().unwrap().take().unwrap());
        assert_eq!(server_connection.message_version, MessageVersion("v1".into()));
        assert_eq!(
            server_connection.remote_endpoint_description.unwrap(),
            EndpointDescription {
                name: Some("a".into()),
                logo_url: Some("b".into()),
                deployment: None,
            }
        );
        assert!(server_connection.remote_node_description.is_none());

        client_connection.transport.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_connection.transport.receive::<String>().await.is_err());

        handle.shutdown();
    }

    #[tokio::test]
    async fn recv_endpoint_config() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, mut server) = setup_server(
            store.clone(),
            Some(EndpointDescription {
                name: Some("a".into()),
                logo_url: Some("b".into()),
                deployment: None,
            }),
            Router::new(),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        let mut client_connection = client.connect(&pairing).await.unwrap();
        assert_eq!(client_connection.message_version, MessageVersion("v1".into()));
        assert_eq!(
            client_connection.remote_endpoint_description.unwrap(),
            EndpointDescription {
                name: Some("a".into()),
                logo_url: Some("b".into()),
                deployment: None,
            }
        );
        assert!(client_connection.remote_node_description.is_none());

        let (requested_pairing, mut server_connection) = server.next_connection().await;
        assert_eq!(requested_pairing, store.last_request.lock().unwrap().take().unwrap());
        assert_eq!(server_connection.message_version, MessageVersion("v1".into()));
        assert!(server_connection.remote_endpoint_description.is_none());
        assert!(server_connection.remote_node_description.is_none());

        client_connection.transport.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_connection.transport.receive::<String>().await.is_err());

        handle.shutdown();
    }

    #[tokio::test]
    async fn send_node_config() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, mut server) = setup_server(store.clone(), None, Router::new()).await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(
                NodeConfig::builder(vec![MessageVersion("v1".into())])
                    .with_node_description(basic_node_description(UUID_A, Role::Rm))
                    .build(),
            ),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        let mut client_connection = client.connect(&pairing).await.unwrap();
        assert_eq!(client_connection.message_version, MessageVersion("v1".into()));
        assert!(client_connection.remote_endpoint_description.is_none());
        assert!(client_connection.remote_node_description.is_none());

        let (requested_pairing, mut server_connection) = server.next_connection().await;
        assert_eq!(requested_pairing, store.last_request.lock().unwrap().take().unwrap());
        assert_eq!(server_connection.message_version, MessageVersion("v1".into()));
        assert!(server_connection.remote_endpoint_description.is_none());
        assert_eq!(server_connection.remote_node_description.unwrap().id, UUID_A.into());

        client_connection.transport.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_connection.transport.receive::<String>().await.is_err());

        handle.shutdown();
    }

    #[tokio::test]
    async fn recv_node_config() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, mut server) = setup_server(store.clone(), None, Router::new()).await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(
                NodeConfig::builder(vec![MessageVersion("v1".into())])
                    .with_node_description(basic_node_description(UUID_B, Role::Cem))
                    .build(),
            ),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        let mut client_connection = client.connect(&pairing).await.unwrap();
        assert_eq!(client_connection.message_version, MessageVersion("v1".into()));
        assert!(client_connection.remote_endpoint_description.is_none());
        assert!(client_connection.remote_node_description.is_none());

        let (requested_pairing, mut server_connection) = server.next_connection().await;
        assert_eq!(requested_pairing, store.last_request.lock().unwrap().take().unwrap());
        assert_eq!(server_connection.message_version, MessageVersion("v1".into()));
        assert!(server_connection.remote_endpoint_description.is_none());
        assert_eq!(server_connection.remote_node_description.unwrap().id, UUID_B.into());

        client_connection.transport.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_connection.transport.receive::<String>().await.is_err());

        handle.shutdown();
    }

    #[tokio::test]
    async fn no_shared_comm_protocol() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, _server) = setup_server(
            store.clone(),
            None,
            Router::new().route(
                "/v1/initiateConnection",
                post(|| async { CommunicationDetailsErrorMessage::IncompatibleCommunicationProtocols }),
            ),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        assert_eq!(client.connect(&pairing).await.unwrap_err().kind(), ErrorKind::NoSupportedVersion);
        assert_eq!(pairing.tokens.lock().unwrap().clone(), vec![AccessToken("testtoken".into())]);

        handle.shutdown();
    }

    #[tokio::test]
    async fn no_shared_message_version() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, _server) = setup_server(
            store.clone(),
            None,
            Router::new().route(
                "/v1/initiateConnection",
                post(|| async { CommunicationDetailsErrorMessage::IncompatibleS2MessageVersions }),
            ),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        assert_eq!(client.connect(&pairing).await.unwrap_err().kind(), ErrorKind::NoSupportedVersion);
        assert_eq!(pairing.tokens.lock().unwrap().clone(), vec![AccessToken("testtoken".into())]);

        handle.shutdown();
    }

    #[tokio::test]
    async fn unknown_comm_protocol() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, _server) = setup_server(
            store.clone(),
            None,
            Router::new().route(
                "/v1/initiateConnection",
                post(|| async {
                    InitiateConnectionResponse {
                        communication_protocol: CommunicationProtocol("Unknown".into()),
                        message_version: MessageVersion("v1".into()),
                        access_token: AccessToken::new(&mut rand::rng()),
                        node_description: None,
                        endpoint_description: None,
                    }
                }),
            ),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        assert_eq!(client.connect(&pairing).await.unwrap_err().kind(), ErrorKind::NoSupportedVersion);
        assert_eq!(pairing.tokens.lock().unwrap().clone(), vec![AccessToken("testtoken".into())]);

        handle.shutdown();
    }

    #[tokio::test]
    async fn unknown_message_version() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, _server) = setup_server(
            store.clone(),
            None,
            Router::new().route(
                "/v1/initiateConnection",
                post(|| async {
                    InitiateConnectionResponse {
                        communication_protocol: CommunicationProtocol("WebSocket".into()),
                        message_version: MessageVersion("v0".into()),
                        access_token: AccessToken::new(&mut rand::rng()),
                        node_description: None,
                        endpoint_description: None,
                    }
                }),
            ),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        assert_eq!(client.connect(&pairing).await.unwrap_err().kind(), ErrorKind::NoSupportedVersion);
        assert_eq!(pairing.tokens.lock().unwrap().clone(), vec![AccessToken("testtoken".into())]);

        handle.shutdown();
    }

    #[tokio::test]
    async fn cannot_persist_token() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, mut server) = setup_server(store.clone(), None, Router::new()).await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        struct NonPersistingPairing {
            client: NodeId,
            server: NodeId,
            tokens: Vec<AccessToken>,
            url: String,
        }

        impl ClientPairing for NonPersistingPairing {
            type Error = std::io::Error;

            fn client_id(&self) -> NodeId {
                self.server
            }

            fn server_id(&self) -> NodeId {
                self.client
            }

            fn access_tokens(&self) -> impl AsRef<[AccessToken]> {
                self.tokens.clone()
            }

            fn communication_url(&self) -> impl AsRef<str> {
                &self.url
            }

            async fn set_access_tokens(&mut self, _tokens: Vec<AccessToken>) -> Result<(), Self::Error> {
                Err(std::io::ErrorKind::Other.into())
            }
        }

        assert!(
            client
                .connect(NonPersistingPairing {
                    client: UUID_A.into(),
                    server: UUID_B.into(),
                    tokens: vec![AccessToken("testtoken".into())],
                    url: format!("https://localhost:{}/", addr.port()),
                })
                .await
                .is_err()
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        let mut client_connection = client.connect(&pairing).await.unwrap();
        assert_eq!(client_connection.message_version, MessageVersion("v1".into()));
        assert!(client_connection.remote_endpoint_description.is_none());
        assert!(client_connection.remote_node_description.is_none());

        let (requested_pairing, mut server_connection) = server.next_connection().await;
        assert_eq!(requested_pairing, store.last_request.lock().unwrap().take().unwrap());
        assert_eq!(server_connection.message_version, MessageVersion("v1".into()));
        assert!(server_connection.remote_endpoint_description.is_none());
        assert!(server_connection.remote_node_description.is_none());

        client_connection.transport.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_connection.transport.receive::<String>().await.is_err());
    }

    #[tokio::test]
    async fn confirmation_failed_server_could_not_store() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, _server) = setup_server(
            store.clone(),
            None,
            Router::new().route("/v1/confirmAccessToken", post(|| async { StatusCode::INTERNAL_SERVER_ERROR })),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        assert_eq!(client.connect(&pairing).await.unwrap_err().kind(), ErrorKind::ProtocolError);
        assert_eq!(*store.token.lock().unwrap(), AccessToken("testtoken".into()));
        assert!(pairing.tokens.lock().unwrap().contains(&AccessToken("testtoken".into())));
    }

    #[tokio::test]
    async fn confirmation_failed_unknown() {
        let store = TestPairingStore::new(
            AccessToken("testtoken".into()),
            NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        );
        let (handle, _server) = setup_server(
            store.clone(),
            None,
            Router::new().route("/v1/confirmAccessToken", post(|| async { StatusCode::UNAUTHORIZED })),
        )
        .await;

        let addr = handle.listening().await.unwrap();
        let client = Client::new(
            ClientConfig {
                additional_certificates: vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
                endpoint_description: None,
            },
            Arc::new(NodeConfig::builder(vec![MessageVersion("v1".into())]).build()),
        );

        let pairing = TestPairing {
            client: UUID_A.into(),
            server: UUID_B.into(),
            tokens: Arc::new(Mutex::new(vec![AccessToken("testtoken".into())])),
            url: format!("https://localhost:{}/", addr.port()),
        };

        assert_eq!(client.connect(&pairing).await.unwrap_err().kind(), ErrorKind::ProtocolError);
        assert_eq!(*store.token.lock().unwrap(), AccessToken("testtoken".into()));
        assert!(pairing.tokens.lock().unwrap().contains(&AccessToken("testtoken".into())));
    }
}
