use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
    time::Duration,
};

use axum::{
    Json, Router,
    extract::State,
    response::{IntoResponse, Response},
    routing::{get, post},
};
use reqwest::StatusCode;
use tracing::{Instrument, info, trace};

use crate::{
    CommunicationProtocol, MessageVersion, S2EndpointDescription, S2NodeDescription, S2NodeId,
    common::{root, websocket_extractor::WebSocketUpgrade, wire::AccessToken},
    communication::{
        ConnectionInfo, NodeConfig, WebSocketTransport,
        wire::{
            CommunicationDetails, CommunicationDetailsErrorMessage, CommunicationToken, InitiateConnectionRequest,
            InitiateConnectionResponse, WebSocketCommunicationDetails,
        },
    },
};

// Maximum number of pending connections on the channel between the actual server handler and the server api.
const BUFFER_SIZE: usize = 1;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
/// A pairing to be looked up.
pub struct PairingLookup {
    /// Identifier of the remote end of the pairing.
    pub client: S2NodeId,
    /// Identifier of the local end of the pairing.
    pub server: S2NodeId,
}

/// Result of looking up a pairing.
pub enum PairingLookupResult<Pairing> {
    /// Pairing exists.
    Pairing(Pairing),
    /// Pairing existed in the past, but has recently unpaired.
    Unpaired,
    /// Pairing never existed, or existed so long ago that that is no longer known.
    NeverPaired,
}

/// Storage provider for the pairings a communication server handles
pub trait ServerPairingStore: Sync + Send + 'static {
    /// Type of the errors generated by this storage provider.
    type Error: std::error::Error;
    /// Type of the pairings provided by this storage provider.
    type Pairing<'a>: ServerPairing<Error = Self::Error> + 'a
    where
        Self: 'a;

    /// Lookup a specific pairing.
    ///
    /// Errors on this function should only result from errors in the interaction with
    /// the actual storage medium. Pairings that do not exist should be returned through
    /// the [`PairingLookupResult`].
    fn lookup(&self, request: PairingLookup) -> impl Future<Output = Result<PairingLookupResult<Self::Pairing<'_>>, Self::Error>> + Send;
}

/// Description of an actual pairing between server and client.
pub trait ServerPairing: Send {
    /// Error type that the storage produces.
    type Error: std::error::Error;

    /// Access token used with this pairing.
    fn access_token(&self) -> impl AsRef<AccessToken>;
    /// Configuration of the local node of this pairing.
    fn config(&self) -> impl AsRef<NodeConfig>;

    /// Change the stored access token for this pairing.
    fn set_access_token(&mut self, token: AccessToken) -> impl Future<Output = Result<(), Self::Error>> + Send;
}

/// Configuration for the S2 connection server.
pub struct ServerConfig {
    /// URL at which the communication server is reachable.
    pub base_url: String,
    /// Updated description of this endpoint to send during communication requests.
    pub endpoint_description: Option<S2EndpointDescription>,
}

/// Server for handling the S2 Communication establishment subprotocol.
pub struct Server<Store> {
    app_state: AppState<Store>,
    connection_receiver: tokio::sync::mpsc::Receiver<(PairingLookup, ConnectionInfo)>,
}

type AppState<Store> = Arc<AppStateInner<Store>>;

struct AppStateInner<Store> {
    store: Store,
    pending_tokens: Mutex<HashMap<AccessToken, Expiring<Session>>>,
    pending_websockets: Mutex<HashMap<CommunicationToken, Expiring<PendingWebsocket>>>,
    base_url: String,
    endpoint_description: Option<S2EndpointDescription>,
    connection_sender: tokio::sync::mpsc::Sender<(PairingLookup, ConnectionInfo)>,
}

struct Expiring<S> {
    start_time: tokio::time::Instant,
    session: S,
}

impl<S> Expiring<S> {
    fn into_state(self) -> Option<S> {
        if self.start_time.elapsed() > Duration::from_secs(15) {
            None
        } else {
            Some(self.session)
        }
    }
}

#[expect(unused)]
struct Session {
    span: tracing::Span,
    lookup: PairingLookup,
    token: AccessToken,
    node_description: Option<S2NodeDescription>,
    endpoint_description: Option<S2EndpointDescription>,
    message_version: MessageVersion,
    communication_protocol: CommunicationProtocol,
}

struct PendingWebsocket {
    lookup: PairingLookup,
    node_description: Option<S2NodeDescription>,
    endpoint_description: Option<S2EndpointDescription>,
    message_version: MessageVersion,
}

impl<Store: ServerPairingStore> Server<Store> {
    /// Create a new server given a configuration and a storage provider for the pairing sessions.
    pub fn new(config: ServerConfig, store: Store) -> Self {
        let (connection_sender, connection_receiver) = tokio::sync::mpsc::channel(BUFFER_SIZE);
        Server {
            app_state: Arc::new(AppStateInner {
                store,
                pending_tokens: Mutex::new(HashMap::new()),
                pending_websockets: Mutex::new(HashMap::new()),
                base_url: config.base_url,
                endpoint_description: config.endpoint_description,
                connection_sender,
            }),
            connection_receiver,
        }
    }

    /// Get an [`axum::Router`] handling the endpoints for the communication protocol.
    ///
    /// Incomming http requests can be handled by this router through the [axum-server](https://docs.rs/axum-server/0.8.0/axum_server/) crate.
    pub fn get_router(&self) -> axum::Router<()> {
        Router::new()
            .route("/", get(root))
            .nest("/v1", v1_router())
            .with_state(self.app_state.clone())
    }

    /// Get the next connection which has been established with the server.
    pub async fn next_connection(&mut self) -> (PairingLookup, ConnectionInfo) {
        // The other end will always exist.
        self.connection_receiver.recv().await.unwrap()
    }
}

impl IntoResponse for CommunicationDetailsErrorMessage {
    fn into_response(self) -> axum::response::Response {
        (StatusCode::BAD_REQUEST, Json(self)).into_response()
    }
}

impl IntoResponse for InitiateConnectionResponse {
    fn into_response(self) -> axum::response::Response {
        Json(self).into_response()
    }
}

fn select_overlap<T: Eq + Clone>(primary: &[T], secondary: &[T]) -> Option<T> {
    for el in primary {
        if secondary.contains(el) {
            return Some(el.clone());
        }
    }

    None
}

fn v1_router<Store: ServerPairingStore>() -> Router<AppState<Store>> {
    Router::new()
        .route("/initiateConnection", post(v1_initiate_connection))
        .route("/confirmAccessToken", post(v1_confirm_access_token))
        .route("/websocket", get(v1_websocket))
}

#[tracing::instrument(skip_all, level = tracing::Level::INFO)]
async fn v1_initiate_connection<Store: ServerPairingStore>(
    State(state): State<AppState<Store>>,
    token: AccessToken,
    Json(request): Json<InitiateConnectionRequest>,
) -> axum::response::Response {
    let session_span = tracing::span!(parent: None, tracing::Level::ERROR, "Communication session", client = %request.client_node_id, server = %request.server_node_id);
    let session_span_clone = session_span.clone();

    async move {
        trace!("Received request for connection initiation.");

        let lookup = PairingLookup {
            client: request.client_node_id,
            server: request.server_node_id,
        };

        let pairing = match state.store.lookup(lookup.clone()).await {
            Ok(PairingLookupResult::Pairing(pairing)) => pairing,
            Ok(PairingLookupResult::Unpaired) => return CommunicationDetailsErrorMessage::NoLongerPaired.into_response(),
            Ok(PairingLookupResult::NeverPaired) => return StatusCode::UNAUTHORIZED.into_response(),
            Err(_) => return StatusCode::INTERNAL_SERVER_ERROR.into_response(),
        };

        trace!("Found pairing.");

        if pairing.access_token().as_ref() != &token {
            info!("Received incorrect access token for connection initiation.");
            return StatusCode::UNAUTHORIZED.into_response();
        }

        let config = pairing.config();

        let Some(communication_protocol) = select_overlap(
            &request.supported_communication_protocols,
            &[CommunicationProtocol("WebSocket".into())],
        ) else {
            info!("No overlap in communication protocols between client and server.");
            return CommunicationDetailsErrorMessage::IncompatibleCommunicationProtocols.into_response();
        };
        let Some(message_version) = select_overlap(&request.supported_message_versions, config.as_ref().supported_message_versions())
        else {
            info!("No overlap in S2 message versions between client and server.");
            return CommunicationDetailsErrorMessage::IncompatibleS2MessageVersions.into_response();
        };

        trace!(
            ?communication_protocol,
            ?message_version,
            "Selected communication protocol and message version."
        );

        let mut pending_tokens = state.pending_tokens.lock().unwrap();

        // Collisions are unlikely but technically possible.
        let new_access_token = loop {
            let candidate = AccessToken::new(&mut rand::rng());
            if !pending_tokens.contains_key(&candidate) {
                break candidate;
            }
        };

        pending_tokens.insert(
            new_access_token.clone(),
            Expiring {
                start_time: tokio::time::Instant::now(),
                session: Session {
                    span: session_span,
                    lookup,
                    token,
                    node_description: request.node_description,
                    endpoint_description: request.endpoint_description,
                    message_version: message_version.clone(),
                    communication_protocol: communication_protocol.clone(),
                },
            },
        );

        trace!("Stored session.");

        InitiateConnectionResponse {
            communication_protocol,
            message_version,
            access_token: new_access_token,
            node_description: config.as_ref().node_description().cloned(),
            endpoint_description: state.endpoint_description.clone(),
        }
        .into_response()
    }
    .instrument(session_span_clone)
    .await
}

impl IntoResponse for CommunicationDetails {
    fn into_response(self) -> axum::response::Response {
        Json(self).into_response()
    }
}

#[tracing::instrument(skip_all, level = tracing::Level::INFO)]
async fn v1_confirm_access_token<Store: ServerPairingStore>(
    State(state): State<AppState<Store>>,
    token: AccessToken,
) -> Result<CommunicationDetails, StatusCode> {
    trace!("Received request to confirm access token.");

    let session = {
        let mut pending_tokens = state.pending_tokens.lock().unwrap();
        pending_tokens
            .remove(&token)
            .and_then(|v| v.into_state())
            .ok_or(StatusCode::UNAUTHORIZED)?
    };

    let session_span_clone = session.span.clone();

    async move {
        trace!("Found session, looking up pairing.");

        let mut pairing = match state.store.lookup(session.lookup.clone()).await {
            Ok(PairingLookupResult::Pairing(pairing)) => pairing,
            Ok(PairingLookupResult::NeverPaired | PairingLookupResult::Unpaired) => return Err(StatusCode::UNAUTHORIZED),
            Err(_) => return Err(StatusCode::UNAUTHORIZED),
        };

        trace!("Found pairing, storing new token.");

        pairing
            .set_access_token(session.token)
            .await
            .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

        trace!("Stored token, returning websocket");

        let websocket_token = {
            let mut pending_websockets = state.pending_websockets.lock().unwrap();
            let websocket_token = loop {
                let websocket_token = CommunicationToken::new(&mut rand::rng());
                if !pending_websockets.contains_key(&websocket_token) {
                    break websocket_token;
                }
            };
            pending_websockets.insert(
                websocket_token.clone(),
                Expiring {
                    start_time: tokio::time::Instant::now(),
                    session: PendingWebsocket {
                        lookup: session.lookup,
                        node_description: session.node_description,
                        endpoint_description: session.endpoint_description,
                        message_version: session.message_version,
                    },
                },
            );
            websocket_token
        };

        Ok(CommunicationDetails::WebSocket(WebSocketCommunicationDetails {
            websocket_token,
            websocket_url: format!("wss://{}/v1/websocket", state.base_url),
        }))
    }
    .instrument(session_span_clone)
    .await
}

async fn v1_websocket<Store: ServerPairingStore>(
    State(state): State<AppState<Store>>,
    token: CommunicationToken,
    ws: WebSocketUpgrade,
) -> Response {
    let Some(pending_websocket) = ({
        let mut pending_websocket = state.pending_websockets.lock().unwrap();

        pending_websocket.remove(&token).and_then(Expiring::into_state)
    }) else {
        return StatusCode::UNAUTHORIZED.into_response();
    };

    ws.on_upgrade(|socket| async move {
        state
            .connection_sender
            .send((
                pending_websocket.lookup,
                ConnectionInfo {
                    remote_node_description: pending_websocket.node_description,
                    remote_endpoint_description: pending_websocket.endpoint_description,
                    message_version: pending_websocket.message_version,
                    transport: WebSocketTransport::new_server(socket),
                },
            ))
            .await
            .ok();
    })
}

#[cfg(test)]
mod tests {
    use std::{
        convert::Infallible,
        net::{Ipv4Addr, SocketAddr},
        sync::{Arc, Mutex},
    };

    use axum::body::Body;
    use axum_server::{Handle, tls_rustls::RustlsConfig};
    use http::StatusCode;
    use http_body_util::BodyExt;
    use rustls::pki_types::{CertificateDer, pem::PemObject};
    use s2energy_common::S2Transport;
    use tokio::{net::TcpListener, time::Instant};
    use tokio_tungstenite::{Connector, connect_async_tls_with_config, tungstenite::ClientRequestBuilder};
    use tower::ServiceExt;
    use tracing::{Level, span};

    use crate::{
        AccessToken, CommunicationProtocol, MessageVersion,
        common::wire::test::{UUID_A, UUID_B},
        communication::{
            NodeConfig, Server, ServerConfig, ServerPairing, ServerPairingStore, WebSocketTransport,
            server::{Expiring, PendingWebsocket, Session},
            wire::{
                CommunicationDetails, CommunicationDetailsErrorMessage, CommunicationToken, InitiateConnectionRequest,
                InitiateConnectionResponse,
            },
        },
    };

    use super::{PairingLookup, PairingLookupResult};

    #[derive(Debug, Clone)]
    struct NoneStore;

    impl ServerPairing for &NoneStore {
        type Error = Infallible;

        fn access_token(&self) -> impl AsRef<AccessToken> {
            unimplemented!() as &AccessToken
        }

        fn config(&self) -> impl AsRef<NodeConfig> {
            unimplemented!() as &NodeConfig
        }

        async fn set_access_token(&mut self, _token: AccessToken) -> Result<(), Self::Error> {
            unimplemented!()
        }
    }

    impl ServerPairingStore for NoneStore {
        type Error = Infallible;

        type Pairing<'a>
            = &'a NoneStore
        where
            Self: 'a;

        async fn lookup(&self, request: PairingLookup) -> Result<PairingLookupResult<Self::Pairing<'_>>, Self::Error> {
            Ok(if request.client == UUID_B.into() && request.server == UUID_A.into() {
                PairingLookupResult::Unpaired
            } else {
                PairingLookupResult::NeverPaired
            })
        }
    }

    #[derive(Debug, Clone)]
    struct TestStore {
        token: Arc<Mutex<AccessToken>>,
        config: NodeConfig,
    }

    impl ServerPairing for &TestStore {
        type Error = Infallible;

        fn access_token(&self) -> impl AsRef<AccessToken> {
            self.token.lock().unwrap().clone()
        }

        fn config(&self) -> impl AsRef<NodeConfig> {
            &self.config
        }

        async fn set_access_token(&mut self, token: AccessToken) -> Result<(), Self::Error> {
            *self.token.lock().unwrap() = token;
            Ok(())
        }
    }

    impl ServerPairingStore for TestStore {
        type Error = Infallible;

        type Pairing<'a>
            = &'a TestStore
        where
            Self: 'a;

        async fn lookup(&self, request: PairingLookup) -> Result<PairingLookupResult<Self::Pairing<'_>>, Self::Error> {
            if request.client == UUID_A.into() && request.server == UUID_B.into() {
                Ok(PairingLookupResult::Pairing(self))
            } else {
                Ok(PairingLookupResult::NeverPaired)
            }
        }
    }

    #[tokio::test]
    async fn version_negotiation() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost:8005".into(),
                endpoint_description: None,
            },
            NoneStore,
        );

        let response = server
            .get_router()
            .oneshot(http::Request::get("/").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        assert_eq!(body, b"[\"v1\"]".as_slice());
    }

    #[tokio::test]
    async fn initiate_communication() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost".into(),
                endpoint_description: None,
            },
            TestStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/initiateConnection")
                    .header(http::header::AUTHORIZATION, "Bearer testtoken")
                    .header(http::header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        serde_json::to_vec(&InitiateConnectionRequest {
                            client_node_id: UUID_A.into(),
                            server_node_id: UUID_B.into(),
                            supported_message_versions: vec![MessageVersion("v1".into())],
                            supported_communication_protocols: vec![CommunicationProtocol("WebSocket".into())],
                            node_description: None,
                            endpoint_description: None,
                        })
                        .unwrap(),
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let response_data: InitiateConnectionResponse = serde_json::from_slice(&body).unwrap();
        assert_eq!(response_data.message_version, MessageVersion("v1".into()));
        assert_eq!(response_data.communication_protocol, CommunicationProtocol("WebSocket".into()));
        assert!(response_data.endpoint_description.is_none());
        assert!(response_data.node_description.is_none());
    }

    #[tokio::test]
    async fn never_paired_initiate() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost:8005".into(),
                endpoint_description: None,
            },
            NoneStore,
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/initiateConnection")
                    .header(http::header::AUTHORIZATION, "Bearer testtoken")
                    .header(http::header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        serde_json::to_vec(&InitiateConnectionRequest {
                            client_node_id: UUID_A.into(),
                            server_node_id: UUID_B.into(),
                            supported_message_versions: vec![MessageVersion("v1".into())],
                            supported_communication_protocols: vec![CommunicationProtocol("WebSocket".into())],
                            node_description: None,
                            endpoint_description: None,
                        })
                        .unwrap(),
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    #[tokio::test]
    async fn unpaired_initiate() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost:8005".into(),
                endpoint_description: None,
            },
            NoneStore,
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/initiateConnection")
                    .header(http::header::AUTHORIZATION, "Bearer testtoken")
                    .header(http::header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        serde_json::to_vec(&InitiateConnectionRequest {
                            client_node_id: UUID_B.into(),
                            server_node_id: UUID_A.into(),
                            supported_message_versions: vec![MessageVersion("v1".into())],
                            supported_communication_protocols: vec![CommunicationProtocol("WebSocket".into())],
                            node_description: None,
                            endpoint_description: None,
                        })
                        .unwrap(),
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let response_data: CommunicationDetailsErrorMessage = serde_json::from_slice(&body).unwrap();
        assert_eq!(response_data, CommunicationDetailsErrorMessage::NoLongerPaired);
    }

    #[tokio::test]
    async fn incorrect_token() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost".into(),
                endpoint_description: None,
            },
            TestStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/initiateConnection")
                    .header(http::header::AUTHORIZATION, "Bearer invalid")
                    .header(http::header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        serde_json::to_vec(&InitiateConnectionRequest {
                            client_node_id: UUID_A.into(),
                            server_node_id: UUID_B.into(),
                            supported_message_versions: vec![MessageVersion("v1".into())],
                            supported_communication_protocols: vec![CommunicationProtocol("WebSocket".into())],
                            node_description: None,
                            endpoint_description: None,
                        })
                        .unwrap(),
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    #[tokio::test]
    async fn no_communication_protocol_shared() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost".into(),
                endpoint_description: None,
            },
            TestStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/initiateConnection")
                    .header(http::header::AUTHORIZATION, "Bearer testtoken")
                    .header(http::header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        serde_json::to_vec(&InitiateConnectionRequest {
                            client_node_id: UUID_A.into(),
                            server_node_id: UUID_B.into(),
                            supported_message_versions: vec![MessageVersion("v1".into())],
                            supported_communication_protocols: vec![CommunicationProtocol("Unknown".into())],
                            node_description: None,
                            endpoint_description: None,
                        })
                        .unwrap(),
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let response_data: CommunicationDetailsErrorMessage = serde_json::from_slice(&body).unwrap();
        assert_eq!(response_data, CommunicationDetailsErrorMessage::IncompatibleCommunicationProtocols);
    }

    #[tokio::test]
    async fn no_message_version_shared() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost".into(),
                endpoint_description: None,
            },
            TestStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/initiateConnection")
                    .header(http::header::AUTHORIZATION, "Bearer testtoken")
                    .header(http::header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        serde_json::to_vec(&InitiateConnectionRequest {
                            client_node_id: UUID_A.into(),
                            server_node_id: UUID_B.into(),
                            supported_message_versions: vec![MessageVersion("v0".into())],
                            supported_communication_protocols: vec![CommunicationProtocol("WebSocket".into())],
                            node_description: None,
                            endpoint_description: None,
                        })
                        .unwrap(),
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let response_data: CommunicationDetailsErrorMessage = serde_json::from_slice(&body).unwrap();
        assert_eq!(response_data, CommunicationDetailsErrorMessage::IncompatibleS2MessageVersions);
    }

    #[tokio::test]
    async fn confirm_access_token() {
        let store = TestStore {
            token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
            config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
        };
        let server = Server::new(
            ServerConfig {
                base_url: "localhost".into(),
                endpoint_description: None,
            },
            store.clone(),
        );
        server.app_state.pending_tokens.lock().unwrap().insert(
            AccessToken("newtoken".into()),
            Expiring {
                start_time: Instant::now(),
                session: Session {
                    span: span!(Level::TRACE, "testspan"),
                    lookup: PairingLookup {
                        client: UUID_A.into(),
                        server: UUID_B.into(),
                    },
                    token: AccessToken("newtoken".into()),
                    node_description: None,
                    endpoint_description: None,
                    message_version: MessageVersion("v1".into()),
                    communication_protocol: CommunicationProtocol("WebSocket".into()),
                },
            },
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/confirmAccessToken")
                    .header(http::header::AUTHORIZATION, "Bearer newtoken")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let CommunicationDetails::WebSocket(response_data) = serde_json::from_slice(&body).unwrap();
        assert_eq!(response_data.websocket_url, "wss://localhost/v1/websocket");
        assert_eq!(store.token.lock().unwrap().clone(), AccessToken("newtoken".into()));
    }

    #[tokio::test]
    async fn confirm_incorrect_token() {
        let server = Server::new(
            ServerConfig {
                base_url: "localhost".into(),
                endpoint_description: None,
            },
            TestStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );
        server.app_state.pending_tokens.lock().unwrap().insert(
            AccessToken("newtoken".into()),
            Expiring {
                start_time: Instant::now(),
                session: Session {
                    span: span!(Level::TRACE, "testspan"),
                    lookup: PairingLookup {
                        client: UUID_A.into(),
                        server: UUID_B.into(),
                    },
                    token: AccessToken("newtoken".into()),
                    node_description: None,
                    endpoint_description: None,
                    message_version: MessageVersion("v1".into()),
                    communication_protocol: CommunicationProtocol("WebSocket".into()),
                },
            },
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/confirmAccessToken")
                    .header(http::header::AUTHORIZATION, "Bearer testtoken")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    #[tokio::test]
    async fn confirm_cant_store_token() {
        struct NoStoreStore {
            token: Arc<Mutex<AccessToken>>,
            config: NodeConfig,
        }

        impl ServerPairing for &NoStoreStore {
            type Error = std::io::Error;

            fn access_token(&self) -> impl AsRef<AccessToken> {
                self.token.lock().unwrap().clone()
            }

            fn config(&self) -> impl AsRef<NodeConfig> {
                &self.config
            }

            async fn set_access_token(&mut self, _token: AccessToken) -> Result<(), Self::Error> {
                Err(std::io::ErrorKind::Other.into())
            }
        }

        impl ServerPairingStore for NoStoreStore {
            type Error = std::io::Error;

            type Pairing<'a>
                = &'a NoStoreStore
            where
                Self: 'a;

            async fn lookup(&self, request: PairingLookup) -> Result<PairingLookupResult<Self::Pairing<'_>>, Self::Error> {
                if request.client == UUID_A.into() && request.server == UUID_B.into() {
                    Ok(PairingLookupResult::Pairing(self))
                } else {
                    Ok(PairingLookupResult::NeverPaired)
                }
            }
        }

        let server = Server::new(
            ServerConfig {
                base_url: "localhost".into(),
                endpoint_description: None,
            },
            NoStoreStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );
        server.app_state.pending_tokens.lock().unwrap().insert(
            AccessToken("newtoken".into()),
            Expiring {
                start_time: Instant::now(),
                session: Session {
                    span: span!(Level::TRACE, "testspan"),
                    lookup: PairingLookup {
                        client: UUID_A.into(),
                        server: UUID_B.into(),
                    },
                    token: AccessToken("newtoken".into()),
                    node_description: None,
                    endpoint_description: None,
                    message_version: MessageVersion("v1".into()),
                    communication_protocol: CommunicationProtocol("WebSocket".into()),
                },
            },
        );

        let response = server
            .get_router()
            .oneshot(
                http::Request::post("/v1/confirmAccessToken")
                    .header(http::header::AUTHORIZATION, "Bearer newtoken")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::INTERNAL_SERVER_ERROR);
    }

    #[tokio::test]
    async fn websocket_handling() {
        let listener = TcpListener::bind(SocketAddr::new(Ipv4Addr::LOCALHOST.into(), 0)).await.unwrap();
        let port = listener.local_addr().unwrap().port();
        let mut server = Server::new(
            ServerConfig {
                base_url: format!("localhost:{}", port),
                endpoint_description: None,
            },
            TestStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );
        server.app_state.pending_websockets.lock().unwrap().insert(
            CommunicationToken("testtoken".into()),
            Expiring {
                start_time: Instant::now(),
                session: PendingWebsocket {
                    lookup: PairingLookup {
                        client: UUID_A.into(),
                        server: UUID_B.into(),
                    },
                    node_description: None,
                    endpoint_description: None,
                    message_version: MessageVersion("v1".into()),
                },
            },
        );
        let rustls_config = RustlsConfig::from_pem(
            include_bytes!("../../testdata/localhost.chain.pem").into(),
            include_bytes!("../../testdata/localhost.key").into(),
        )
        .await
        .unwrap();
        let http_server_handle = Handle::new();
        let axum_server = axum_server::from_tcp_rustls(listener.into_std().unwrap(), rustls_config)
            .unwrap()
            .handle(http_server_handle.clone())
            .serve(server.get_router().into_make_service());
        tokio::spawn(async move {
            axum_server.await.unwrap();
        });

        let tls_config_builder = rustls::ClientConfig::builder();
        let cert_verifier = rustls_platform_verifier::Verifier::new_with_extra_roots(
            vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
            tls_config_builder.crypto_provider().clone(),
        )
        .unwrap();
        let tls_config = tls_config_builder
            .dangerous()
            .with_custom_certificate_verifier(Arc::new(cert_verifier))
            .with_no_client_auth();

        let request = ClientRequestBuilder::new(format!("wss://localhost:{}/v1/websocket", port).try_into().unwrap())
            .with_header(http::header::AUTHORIZATION.as_str(), format!("Bearer testtoken"));

        let (client_socket, _) = connect_async_tls_with_config(request, None, false, Some(Connector::Rustls(Arc::new(tls_config))))
            .await
            .unwrap();

        let (_, mut server_connection) = server.next_connection().await;

        let mut client_socket = WebSocketTransport::new_client(client_socket);

        client_socket.send("hello world").await.unwrap();
        let recv = server_connection.transport.receive::<String>().await.unwrap();
        assert_eq!(recv, "hello world");
        server_connection.transport.disconnect().await;
        assert!(client_socket.receive::<String>().await.is_err());

        http_server_handle.shutdown();
    }

    #[tokio::test]
    async fn websocket_invalid_token() {
        let listener = TcpListener::bind(SocketAddr::new(Ipv4Addr::LOCALHOST.into(), 0)).await.unwrap();
        let port = listener.local_addr().unwrap().port();
        let server = Server::new(
            ServerConfig {
                base_url: format!("localhost:{}", port),
                endpoint_description: None,
            },
            TestStore {
                token: Arc::new(Mutex::new(AccessToken("testtoken".into()))),
                config: NodeConfig::builder(vec![MessageVersion("v1".into())]).build(),
            },
        );
        server.app_state.pending_websockets.lock().unwrap().insert(
            CommunicationToken("testtoken".into()),
            Expiring {
                start_time: Instant::now(),
                session: PendingWebsocket {
                    lookup: PairingLookup {
                        client: UUID_A.into(),
                        server: UUID_B.into(),
                    },
                    node_description: None,
                    endpoint_description: None,
                    message_version: MessageVersion("v1".into()),
                },
            },
        );
        let rustls_config = RustlsConfig::from_pem(
            include_bytes!("../../testdata/localhost.chain.pem").into(),
            include_bytes!("../../testdata/localhost.key").into(),
        )
        .await
        .unwrap();
        let http_server_handle = Handle::new();
        let axum_server = axum_server::from_tcp_rustls(listener.into_std().unwrap(), rustls_config)
            .unwrap()
            .handle(http_server_handle.clone())
            .serve(server.get_router().into_make_service());
        tokio::spawn(async move {
            axum_server.await.unwrap();
        });

        let tls_config_builder = rustls::ClientConfig::builder();
        let cert_verifier = rustls_platform_verifier::Verifier::new_with_extra_roots(
            vec![CertificateDer::from_pem_slice(include_bytes!("../../testdata/root.pem")).unwrap()],
            tls_config_builder.crypto_provider().clone(),
        )
        .unwrap();
        let tls_config = tls_config_builder
            .dangerous()
            .with_custom_certificate_verifier(Arc::new(cert_verifier))
            .with_no_client_auth();

        let request = ClientRequestBuilder::new(format!("wss://localhost:{}/v1/websocket", port).try_into().unwrap())
            .with_header(http::header::AUTHORIZATION.as_str(), format!("Bearer invalidtoken"));

        assert!(
            connect_async_tls_with_config(request, None, false, Some(Connector::Rustls(Arc::new(tls_config))))
                .await
                .is_err()
        );

        http_server_handle.shutdown();
    }
}
