use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
    time::Duration,
};

use axum::{
    Json, Router,
    extract::State,
    response::{IntoResponse, Response},
    routing::{get, post},
};
use reqwest::StatusCode;
use tracing::{Instrument, info, trace};

use crate::{
    CommunicationProtocol, MessageVersion, S2EndpointDescription, S2NodeDescription, S2NodeId,
    common::{root, websocket_extractor::WebSocketUpgrade, wire::AccessToken},
    communication::{
        ConnectionInfo, NodeConfig, WebSocketTransport,
        wire::{
            CommunicationDetails, CommunicationDetailsErrorMessage, CommunicationToken, InitiateConnectionRequest,
            InitiateConnectionResponse, WebSocketCommunicationDetails,
        },
    },
};

// Maximum number of pending connections on the channel between the actual server handler and the server api.
const BUFFER_SIZE: usize = 1;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
/// A pairing to be looked up.
pub struct PairingLookup {
    /// Identifier of the remote end of the pairing.
    pub client: S2NodeId,
    /// Identifier of the local end of the pairing.
    pub server: S2NodeId,
}

/// Result of looking up a pairing.
pub enum PairingLookupResult<Pairing> {
    /// Pairing exists.
    Pairing(Pairing),
    /// Pairing existed in the past, but has recently unpaired.
    Unpaired,
    /// Pairing never existed, or existed so long ago that that is no longer known.
    NeverPaired,
}

/// Storage provider for the pairings a communication server handles
pub trait ServerPairingStore: Sync + Send + 'static {
    /// Type of the errors generated by this storage provider.
    type Error: std::error::Error;
    /// Type of the pairings provided by this storage provider.
    type Pairing<'a>: ServerPairing<Error = Self::Error> + 'a
    where
        Self: 'a;

    /// Lookup a specific pairing.
    ///
    /// Errors on this function should only result from errors in the interaction with
    /// the actual storage medium. Pairings that do not exist should be returned through
    /// the [`PairingLookupResult`].
    fn lookup(&self, request: PairingLookup) -> impl Future<Output = Result<PairingLookupResult<Self::Pairing<'_>>, Self::Error>> + Send;
}

/// Description of an actual pairing between server and client.
pub trait ServerPairing: Send {
    /// Error type that the storage produces.
    type Error: std::error::Error;

    /// Access token used with this pairing.
    fn access_token(&self) -> impl AsRef<AccessToken>;
    /// Configuration of the local node of this pairing.
    fn config(&self) -> impl AsRef<NodeConfig>;

    /// Change the stored access token for this pairing.
    fn set_access_token(&mut self, token: AccessToken) -> impl Future<Output = Result<(), Self::Error>> + Send;
}

/// Configuration for the S2 connection server.
pub struct ServerConfig {
    /// URL at which the communication server is reachable.
    pub base_url: String,
    /// Updated description of this endpoint to send during communication requests.
    pub endpoint_description: Option<S2EndpointDescription>,
}

/// Server for handling the S2 Communication establishment subprotocol.
pub struct Server<Store> {
    app_state: AppState<Store>,
    connection_receiver: tokio::sync::mpsc::Receiver<(PairingLookup, ConnectionInfo)>,
}

type AppState<Store> = Arc<AppStateInner<Store>>;

struct AppStateInner<Store> {
    store: Store,
    pending_tokens: Mutex<HashMap<AccessToken, Expiring<Session>>>,
    pending_websockets: Mutex<HashMap<CommunicationToken, Expiring<PendingWebsocket>>>,
    base_url: String,
    endpoint_description: Option<S2EndpointDescription>,
    connection_sender: tokio::sync::mpsc::Sender<(PairingLookup, ConnectionInfo)>,
}

struct Expiring<S> {
    start_time: tokio::time::Instant,
    session: S,
}

impl<S> Expiring<S> {
    fn into_state(self) -> Option<S> {
        if self.start_time.elapsed() > Duration::from_secs(15) {
            None
        } else {
            Some(self.session)
        }
    }
}

#[expect(unused)]
struct Session {
    span: tracing::Span,
    lookup: PairingLookup,
    token: AccessToken,
    node_description: Option<S2NodeDescription>,
    endpoint_description: Option<S2EndpointDescription>,
    message_version: MessageVersion,
    communication_protocol: CommunicationProtocol,
}

struct PendingWebsocket {
    lookup: PairingLookup,
    node_description: Option<S2NodeDescription>,
    endpoint_description: Option<S2EndpointDescription>,
    message_version: MessageVersion,
}

impl<Store: ServerPairingStore> Server<Store> {
    /// Create a new server given a configuration and a storage provider for the pairing sessions.
    pub fn new(config: ServerConfig, store: Store) -> Self {
        let (connection_sender, connection_receiver) = tokio::sync::mpsc::channel(BUFFER_SIZE);
        Server {
            app_state: Arc::new(AppStateInner {
                store,
                pending_tokens: Mutex::new(HashMap::new()),
                pending_websockets: Mutex::new(HashMap::new()),
                base_url: config.base_url,
                endpoint_description: config.endpoint_description,
                connection_sender,
            }),
            connection_receiver,
        }
    }

    /// Get an [`axum::Router`] handling the endpoints for the communication protocol.
    ///
    /// Incomming http requests can be handled by this router through the [axum-server](https://docs.rs/axum-server/0.8.0/axum_server/) crate.
    pub fn get_router(&self) -> axum::Router<()> {
        Router::new()
            .route("/", get(root))
            .nest("/v1", v1_router())
            .with_state(self.app_state.clone())
    }

    /// Get the next connection which has been established with the server.
    pub async fn next_connection(&mut self) -> (PairingLookup, ConnectionInfo) {
        // The other end will always exist.
        self.connection_receiver.recv().await.unwrap()
    }
}

impl IntoResponse for CommunicationDetailsErrorMessage {
    fn into_response(self) -> axum::response::Response {
        (StatusCode::BAD_REQUEST, Json(self)).into_response()
    }
}

impl IntoResponse for InitiateConnectionResponse {
    fn into_response(self) -> axum::response::Response {
        Json(self).into_response()
    }
}

fn select_overlap<T: Eq + Clone>(primary: &[T], secondary: &[T]) -> Option<T> {
    for el in primary {
        if secondary.contains(el) {
            return Some(el.clone());
        }
    }

    None
}

fn v1_router<Store: ServerPairingStore>() -> Router<AppState<Store>> {
    Router::new()
        .route("/initiateConnection", post(v1_initiate_connection))
        .route("/confirmAccessToken", post(v1_confirm_access_token))
        .route("/websocket", get(v1_websocket))
}

#[tracing::instrument(skip_all, level = tracing::Level::INFO)]
async fn v1_initiate_connection<Store: ServerPairingStore>(
    State(state): State<AppState<Store>>,
    token: AccessToken,
    Json(request): Json<InitiateConnectionRequest>,
) -> axum::response::Response {
    let session_span = tracing::span!(parent: None, tracing::Level::ERROR, "Communication session", client = %request.client_node_id, server = %request.server_node_id);
    let session_span_clone = session_span.clone();

    async move {
        trace!("Received request for connection initiation.");

        let lookup = PairingLookup {
            client: request.client_node_id,
            server: request.server_node_id,
        };

        let pairing = match state.store.lookup(lookup.clone()).await {
            Ok(PairingLookupResult::Pairing(pairing)) => pairing,
            Ok(PairingLookupResult::Unpaired) => return CommunicationDetailsErrorMessage::NoLongerPaired.into_response(),
            Ok(PairingLookupResult::NeverPaired) => return StatusCode::UNAUTHORIZED.into_response(),
            Err(_) => return StatusCode::INTERNAL_SERVER_ERROR.into_response(),
        };

        trace!("Found pairing.");

        if pairing.access_token().as_ref() != &token {
            info!("Received incorrect access token for connection initiation.");
            return StatusCode::UNAUTHORIZED.into_response();
        }

        let config = pairing.config();

        let Some(communication_protocol) = select_overlap(
            &request.supported_communication_protocols,
            &[CommunicationProtocol("WebSocket".into())],
        ) else {
            info!("No overlap in communication protocols between client and server.");
            return CommunicationDetailsErrorMessage::IncompatibleCommunicationProtocols.into_response();
        };
        let Some(message_version) = select_overlap(&request.supported_message_versions, config.as_ref().supported_message_versions())
        else {
            info!("No overlap in S2 message versions between client and server.");
            return CommunicationDetailsErrorMessage::IncompatibleS2MessageVersions.into_response();
        };

        trace!(
            ?communication_protocol,
            ?message_version,
            "Selected communication protocol and message version."
        );

        let mut pending_tokens = state.pending_tokens.lock().unwrap();

        // Collisions are unlikely but technically possible.
        let new_access_token = loop {
            let candidate = AccessToken::new(&mut rand::rng());
            if !pending_tokens.contains_key(&candidate) {
                break candidate;
            }
        };

        pending_tokens.insert(
            new_access_token.clone(),
            Expiring {
                start_time: tokio::time::Instant::now(),
                session: Session {
                    span: session_span,
                    lookup,
                    token,
                    node_description: request.node_description,
                    endpoint_description: request.endpoint_description,
                    message_version: message_version.clone(),
                    communication_protocol: communication_protocol.clone(),
                },
            },
        );

        trace!("Stored session.");

        InitiateConnectionResponse {
            communication_protocol,
            message_version,
            access_token: new_access_token,
            node_description: config.as_ref().node_description().cloned(),
            endpoint_description: state.endpoint_description.clone(),
        }
        .into_response()
    }
    .instrument(session_span_clone)
    .await
}

impl IntoResponse for CommunicationDetails {
    fn into_response(self) -> axum::response::Response {
        Json(self).into_response()
    }
}

#[tracing::instrument(skip_all, level = tracing::Level::INFO)]
async fn v1_confirm_access_token<Store: ServerPairingStore>(
    State(state): State<AppState<Store>>,
    token: AccessToken,
) -> Result<CommunicationDetails, StatusCode> {
    trace!("Received request to confirm access token.");

    let session = {
        let mut pending_tokens = state.pending_tokens.lock().unwrap();
        pending_tokens
            .remove(&token)
            .and_then(|v| v.into_state())
            .ok_or(StatusCode::UNAUTHORIZED)?
    };

    let session_span_clone = session.span.clone();

    async move {
        trace!("Found session, looking up pairing.");

        let websocket_token = {
            let mut pending_websockets = state.pending_websockets.lock().unwrap();
            let websocket_token = loop {
                let websocket_token = CommunicationToken::new(&mut rand::rng());
                if !pending_websockets.contains_key(&websocket_token) {
                    break websocket_token;
                }
            };
            pending_websockets.insert(
                websocket_token.clone(),
                Expiring {
                    start_time: tokio::time::Instant::now(),
                    session: PendingWebsocket {
                        lookup: session.lookup,
                        node_description: session.node_description,
                        endpoint_description: session.endpoint_description,
                        message_version: session.message_version,
                    },
                },
            );
            websocket_token
        };

        Ok(CommunicationDetails::WebSocket(WebSocketCommunicationDetails {
            websocket_token,
            websocket_url: format!("wss://{}/v1/websocket", state.base_url),
        }))
    }
    .instrument(session_span_clone)
    .await
}

async fn v1_websocket<Store: ServerPairingStore>(
    State(state): State<AppState<Store>>,
    token: CommunicationToken,
    ws: WebSocketUpgrade,
) -> Response {
    let Some(pending_websocket) = ({
        let mut pending_websocket = state.pending_websockets.lock().unwrap();

        pending_websocket.remove(&token).and_then(Expiring::into_state)
    }) else {
        return StatusCode::UNAUTHORIZED.into_response();
    };

    ws.on_upgrade(|socket| async move {
        state
            .connection_sender
            .send((
                pending_websocket.lookup,
                ConnectionInfo {
                    remote_node_description: pending_websocket.node_description,
                    remote_endpoint_description: pending_websocket.endpoint_description,
                    message_version: pending_websocket.message_version,
                    transport: WebSocketTransport::new_server(socket),
                },
            ))
            .await
            .ok();
    })
}
